title: ☼Vox Uristi☼
description: Create beautiful renders of your Dwarf Fortress game
github_username: plule
minimal_mistakes_skin: sunrise
url: https://plule.github.io
baseurl: /minimal-mistake-test
repository: plule/minimal-mistake-test
logo: /assets/icon.png
compress_html:
  clippings: all

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
