title: ☼Vox Uristi☼
logo: /assets/icon.png
description: Create beautiful renders of your Dwarf Fortress game
show_downloads: true
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
